server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/users
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
